server.port=8080
spring.application.name=api-gateway

# Eureka Connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#exclude spring starter dependency
spring.main.web-application-type=reactive

#If  **kept** security enabled, will use this format (replace `password` with the one from the Discovery Server console):
#eureka.client.service-url.defaultZone=http://user:YOUR_GENERATED_PASSWORD@localhost:8761/eureka/

# --- ROUTING CONFIGURATION ---

# Route for User Service
spring.cloud.gateway.routes[0].id=kisan-user
spring.cloud.gateway.routes[0].uri=lb://kisan-user
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**

# Route for Marketplace Service
spring.cloud.gateway.routes[1].id=kisan-marketplace
spring.cloud.gateway.routes[1].uri=lb://kisan-marketplace
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/marketplace/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/marketplace/(?<segment>.*), /$\{segment}

# Route for Knowledge Service
spring.cloud.gateway.routes[2].id=kisan-knowledge
spring.cloud.gateway.routes[2].uri=lb://kisan-knowledge
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/knowledge/**


# CORS configuration for Angular Frontend
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*